#!/bin/sh
# Regenerate the tables and figures from results/.
# A failing step is reported as a failure and the script exits non-zero.
export PYTHONPATH=$PWD/src:$PWD/experiments:$PWD/figures:$PYTHONPATH
command -v python >/dev/null 2>&1 || { echo "ERROR: no 'python' on PATH. Create and activate the virtualenv first (see README), or put python3 on PATH as python."; exit 127; }
fail=0
t=$(mktemp); trap 'rm -f "$t"' EXIT
echo "-- inflating compressed result files"; for f in $(find results -name "*.csv.gz"); do gunzip -kf "$f"; done
echo "-- ingest results -> tables/figures csv"; if ( cd figures && python ingest_results.py && cd .. ) >"$t" 2>&1; then cat "$t"; else cat "$t"; if grep -qE "FileNotFoundError|No such file|No objects to concatenate" "$t"; then echo "   not regenerated: ingest results -> tables/figures csv -- an input is not present. Per-record outputs are withheld under a data-use agreement (README, Data not included); the shipped figure/table stands."; else echo "   FAILED: ingest results -> tables/figures csv"; fail=1; fi; fi
echo "-- cohort and main-results tables"; if ( cd figures && python make_tables.py && cd .. ) >"$t" 2>&1; then cat "$t"; else cat "$t"; if grep -qE "FileNotFoundError|No such file|No objects to concatenate" "$t"; then echo "   not regenerated: cohort and main-results tables -- an input is not present. Per-record outputs are withheld under a data-use agreement (README, Data not included); the shipped figure/table stands."; else echo "   FAILED: cohort and main-results tables"; fail=1; fi; fi
echo "-- figures (pgfplots sources)"; if ( cd figures && python make_pgf.py && cd .. ) >"$t" 2>&1; then cat "$t"; else cat "$t"; if grep -qE "FileNotFoundError|No such file|No objects to concatenate" "$t"; then echo "   not regenerated: figures (pgfplots sources) -- an input is not present. Per-record outputs are withheld under a data-use agreement (README, Data not included); the shipped figure/table stands."; else echo "   FAILED: figures (pgfplots sources)"; fail=1; fi; fi
echo "-- H1 paired table"; if ( python experiments/h1_paired.py ) >"$t" 2>&1; then cat "$t"; else cat "$t"; if grep -qE "FileNotFoundError|No such file|No objects to concatenate" "$t"; then echo "   not regenerated: H1 paired table -- an input is not present. Per-record outputs are withheld under a data-use agreement (README, Data not included); the shipped figure/table stands."; else echo "   FAILED: H1 paired table"; fail=1; fi; fi
echo "-- sensitivity table"; if ( cd figures && python sensitivity_compare.py && cd .. ) >"$t" 2>&1; then cat "$t"; else cat "$t"; if grep -qE "FileNotFoundError|No such file|No objects to concatenate" "$t"; then echo "   not regenerated: sensitivity table -- an input is not present. Per-record outputs are withheld under a data-use agreement (README, Data not included); the shipped figure/table stands."; else echo "   FAILED: sensitivity table"; fail=1; fi; fi
echo "-- MIMIC-IV table and macros"; if ( cd figures && python make_mimic_table.py && cd .. ) >"$t" 2>&1; then cat "$t"; else cat "$t"; if grep -qE "FileNotFoundError|No such file|No objects to concatenate" "$t"; then echo "   not regenerated: MIMIC-IV table and macros -- an input is not present. Per-record outputs are withheld under a data-use agreement (README, Data not included); the shipped figure/table stands."; else echo "   FAILED: MIMIC-IV table and macros"; fail=1; fi; fi
echo "-- schema-width macros"; if ( cd figures && python make_maskwide_table.py && cd .. ) >"$t" 2>&1; then cat "$t"; else cat "$t"; if grep -qE "FileNotFoundError|No such file|No objects to concatenate" "$t"; then echo "   not regenerated: schema-width macros -- an input is not present. Per-record outputs are withheld under a data-use agreement (README, Data not included); the shipped figure/table stands."; else echo "   FAILED: schema-width macros"; fail=1; fi; fi
echo "-- H_exc and iota macros"; if ( cd figures && python make_lens_macros.py && cd .. ) >"$t" 2>&1; then cat "$t"; else cat "$t"; if grep -qE "FileNotFoundError|No such file|No objects to concatenate" "$t"; then echo "   not regenerated: H_exc and iota macros -- an input is not present. Per-record outputs are withheld under a data-use agreement (README, Data not included); the shipped figure/table stands."; else echo "   FAILED: H_exc and iota macros"; fail=1; fi; fi
echo "-- synthetic suite table and macros"; if ( cd figures && python make_synth_table.py && cd .. ) >"$t" 2>&1; then cat "$t"; else cat "$t"; if grep -qE "FileNotFoundError|No such file|No objects to concatenate" "$t"; then echo "   not regenerated: synthetic suite table and macros -- an input is not present. Per-record outputs are withheld under a data-use agreement (README, Data not included); the shipped figure/table stands."; else echo "   FAILED: synthetic suite table and macros"; fail=1; fi; fi
echo "-- diagnostic validation macros"; if ( cd figures && python make_diagval_table.py && cd .. ) >"$t" 2>&1; then cat "$t"; else cat "$t"; if grep -qE "FileNotFoundError|No such file|No objects to concatenate" "$t"; then echo "   not regenerated: diagnostic validation macros -- an input is not present. Per-record outputs are withheld under a data-use agreement (README, Data not included); the shipped figure/table stands."; else echo "   FAILED: diagnostic validation macros"; fail=1; fi; fi
[ "$fail" -eq 0 ] || { echo; echo "reproduce.sh: one or more steps FAILED (see above)."; exit 1; }
echo; echo "reproduce.sh: no step failed."
