"""tables/runtime.tex from results/runtime_single_fit.csv (experiments/structure_stats.py): wall-clock seconds of
one fit + predict per method on one 80/20 split of the 40,000-record analysis sample, Apple M5, 10 cores."""
import pathlib
import pandas as pd
ROOT = pathlib.Path(__file__).resolve().parent.parent
NAMES = [("mean_impute", "Mean + logistic"), ("mean_indicator", "Mean + indicator"), ("histgb_native", "HistGradientBoosting"),
         ("pattern_submodels", "Pattern submodels"), ("ours", "Proposed method")]
COH = ["colorectal", "lung", "ovarian", "prostate"]
d = pd.read_csv(ROOT / "results/runtime_single_fit.csv"); piv = d.pivot(index="method", columns="cohort", values="seconds")
assert set(COH) <= set(piv.columns) and all(m in piv.index for m, _ in NAMES)
lines = ["% GENERATED by figures/make_runtime_table.py --- do not edit by hand.", r"\begin{table}[t]", r"\centering", r"\small",
         r"\caption{Wall-clock seconds for one fit and one prediction per method on one 80/20 split of the 40{,}000-record analysis sample "
         r"(32{,}000 training records; Apple M5, 10 cores). A full run of ten seeds $\times$ five folds is fifty such fits.}",
         r"\label{tbl:runtime}", r"\begin{tabular}{lrrrr}", r"\toprule", "Method & " + " & ".join(c.capitalize() for c in COH) + r" \\", r"\midrule"]
for m, label in NAMES:
    lines.append(f"{label} & " + " & ".join(f"{piv.loc[m, c]:.1f}" for c in COH) + r" \\")
lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
(ROOT / "tables/runtime.tex").write_text("\n".join(lines) + "\n")
r = piv.loc["ours"] / piv.loc["mean_impute"]; print("  wrote tables/runtime.tex; ours/mean_impute ratio: " + " ".join(f"{c} {r[c]:.0f}x" for c in COH))
