"""tables/tuneboost.tex and tables/tuneboost_counts.tex from results/tune_boost_*.csv (Result 231).

The three boosters, default and tuned, on the four PLCO cohorts and MIMIC-IV. The HistGB column is
Result 171's tune_tree_*.csv, the same protocol on the same platform.

Generated rather than typed because TUNEBOOST's X3 failed by four thousandths on two cohorts: a
prose claim about whether three numbers agree within a floor is exactly the kind that goes stale
silently when the numbers are re-run.
"""
import glob, pathlib
import pandas as pd

ROOT = pathlib.Path(__file__).resolve().parent.parent
PLCO = ["colorectal", "lung", "ovarian", "prostate"]
FLOOR = 0.002

b = pd.concat([pd.read_csv(f) for f in sorted(glob.glob(str(ROOT / "results/tune_boost_*.csv")))])
hist = {}
for f in sorted(glob.glob(str(ROOT / "results/tune_tree_*.csv"))):
    t = pd.read_csv(f)
    hist[t.cohort.iloc[0]] = (t.auprc_default.mean(), t.auprc_tuned.mean())
main = pd.read_csv(ROOT / "figures/real_results.csv").set_index("method")
order = [c for c in PLCO + ["mimic4"] if c in set(b.cohort)]
NAME = {"mimic4": "MIMIC-IV"}


def cell(a, c):
    return b[(b.algo == a) & (b.cohort == c)]


rows = []
for c in order:
    r = {"cohort": NAME.get(c, c.capitalize())}
    for a, key in (("xgboost", "xgb"), ("lightgbm", "lgb")):
        s = cell(a, c)
        r[f"{key}_d"], r[f"{key}_t"] = s.auprc_default.mean(), s.auprc_tuned.mean()
        r[f"{key}_g"] = float((s.auprc_tuned - s.auprc_default).median())
    r["hgb_d"], r["hgb_t"] = hist.get(c, (float("nan"), float("nan")))
    r["spread"] = max(r["xgb_t"], r["lgb_t"], r["hgb_t"]) - min(r["xgb_t"], r["lgb_t"], r["hgb_t"])
    rows.append(r)

lines = ["% GENERATED by figures/make_tuneboost_table.py --- do not edit by hand.",
         r"\begin{table}[t]", r"\centering", r"\small",
         r"\caption{Tuning the three gradient boosters. Mean AUPRC at library defaults and with a "
         r"24-point grid chosen by inner 3-fold cross-validation, 3 seeds $\times$ 5 folds on the "
         r"analysis sample. The grids share four axes (depth, learning rate, number of trees, "
         r"minimum leaf) in each library's own spelling. The histogram column is the earlier run of "
         r"the same protocol. \emph{Spread} is the range of the three tuned means; it exceeds the "
         r"$0.002$ attainable-gain floor on Ovarian and Prostate, which is why the three are "
         r"reported separately rather than as a single tuned tree. Not paired with the main table, "
         r"which uses 10 seeds and different partitions, so no test is reported.}",
         r"\label{tbl:tuneboost}", r"\begin{tabular}{lrrrrrrr}", r"\toprule",
         r"& \multicolumn{2}{c}{XGBoost} & \multicolumn{2}{c}{LightGBM} & "
         r"\multicolumn{2}{c}{Histogram} & \\",
         r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}",
         r"Cohort & Default & Tuned & Default & Tuned & Default & Tuned & Spread \\", r"\midrule"]
for r in rows:
    lines.append(f"{r['cohort']} & {r['xgb_d']:.4f} & {r['xgb_t']:.4f} & {r['lgb_d']:.4f} & "
                 f"{r['lgb_t']:.4f} & {r['hgb_d']:.4f} & {r['hgb_t']:.4f} & {r['spread']:.4f} \\\\")
lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
(ROOT / "tables/tuneboost.tex").write_text("\n".join(lines) + "\n")

p = [r for r in rows if r["cohort"] != "MIMIC-IV"]
xg = [r["xgb_g"] for r in p]
lg = [r["lgb_g"] for r in p]
spreads = [r["spread"] for r in p]
agree = sum(1 for s in spreads if s <= FLOOR)
ahead = sum(1 for r, c in zip(p, PLCO) for k in ("xgb_t", "lgb_t")
            if r[k] > float(main.loc["Proposed method", c]))
beat = sum(1 for r, c in zip(p, PLCO)
           if max(r["xgb_t"], r["lgb_t"]) > float(main.loc["Mean + logistic", c]))
cells = int((b.groupby(["algo", "cohort"]).size() > 0).sum())
m = ["% GENERATED by figures/make_tuneboost_table.py --- do not edit by hand.",
     f"\\newcommand{{\\TbCells}}{{{cells}}}",
     f"\\newcommand{{\\TbXgbGainLo}}{{{min(xg):+.4f}}}",
     f"\\newcommand{{\\TbXgbGainHi}}{{{max(xg):+.4f}}}",
     f"\\newcommand{{\\TbLgbGainLo}}{{{min(lg):+.4f}}}",
     f"\\newcommand{{\\TbLgbGainHi}}{{{max(lg):+.4f}}}",
     f"\\newcommand{{\\TbSpreadLo}}{{{min(spreads):.4f}}}",
     f"\\newcommand{{\\TbSpreadHi}}{{{max(spreads):.4f}}}",
     f"\\newcommand{{\\TbAgree}}{{{agree}}}",
     f"\\newcommand{{\\TbCohorts}}{{{len(p)}}}",
     f"\\newcommand{{\\TbAhead}}{{{ahead}}}",
     f"\\newcommand{{\\TbAheadOf}}{{{2 * len(p)}}}",
     f"\\newcommand{{\\TbBeatImpute}}{{{beat}}}"]
(ROOT / "tables/tuneboost_counts.tex").write_text("\n".join(m) + "\n")
print("  wrote tables/tuneboost.tex and tables/tuneboost_counts.tex")
print("  " + " ".join(x.split('{')[1].rstrip('}') + "=" + x.split('{')[-1].rstrip('}') for x in m[1:]))
