"""Emit tables/hexc_plco.tex and tables/iota_cohorts.tex from committed files.

Both were written by hand until 2026-09-23 from the same two sources this reads:
  figures/hexc_lens_summary.csv  (hexc_lens.py; H_exc mean and sd over 5 permutation seeds)
  results/gate.csv               (baseline feature set, full cohort and the n=40,000 subsample)
The generated macros reproduce the hand-written ones exactly.
"""
import pathlib

import pandas as pd

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
OUT = ROOT / "tables"
NAME = {"colorectal": "Colorectal", "lung": "Lung", "ovarian": "Ovarian",
        "prostate": "Prostate", "mimic4": "Mimic"}
PLCO = ["colorectal", "lung", "ovarian", "prostate"]


def write(path, header, macros):
    with open(path, "w") as f:
        f.write(f"% {header} -- do not edit\n")
        for k, v in macros:
            f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
    print(f"{path.name} written ({len(macros)} macros)")


def hexc():
    s = pd.read_csv(HERE / "hexc_lens_summary.csv").set_index("cohort")
    missing = [c for c in NAME if c not in s.index]
    if missing:
        raise SystemExit(f"hexc_lens_summary.csv lacks {missing}; rerun hexc_lens.py --mimic")
    macros = []
    for c in NAME:
        r = s.loc[c]
        macros += [(f"Hexc{NAME[c]}", f"{r.H_exc_mean:+.2f} \\pm {r.H_exc_sd:.2f}"),
                   (f"Hreal{NAME[c]}", f"{r.H_real:.2f}")]
    write(OUT / "hexc_plco.tex", "generated by figures/make_lens_macros.py from figures/hexc_lens_summary.csv", macros)


def iota():
    g = pd.read_csv(ROOT / "results" / "gate.csv")
    g = g[g.feature_set == "baseline"].set_index(["cohort", "subsample"]).iota
    full = {c: g[(c, "full")] for c in PLCO}
    sub = {c: g[(c, "n40000")] for c in PLCO}
    macros = []
    for c in PLCO:
        macros += [(f"IotaFull{NAME[c]}", f"{full[c]:.3f}"), (f"IotaSub{NAME[c]}", f"{sub[c]:.3f}")]
    macros += [("IotaFullMin", f"{min(full.values()):.3f}"), ("IotaFullMax", f"{max(full.values()):.3f}"),
               ("IotaSubMin", f"{min(sub.values()):.3f}"), ("IotaSubMax", f"{max(sub.values()):.3f}"),
               ("IotaFullSpan", f"{max(full.values()) - min(full.values()):.3f}")]
    write(OUT / "iota_cohorts.tex", "generated by figures/make_lens_macros.py from results/gate.csv (baseline feature set)", macros)


if __name__ == "__main__":
    hexc()
    iota()
