"""tables/semisynth.tex from results/semisynth_*.csv (SHOWCASE.md item D): AUPRC of each arm against the regime
coefficient difference delta, on real masks and values (dev halves), outcome regenerated."""
import glob, pathlib
import pandas as pd
ROOT = pathlib.Path(__file__).resolve().parent.parent
NAMES = {"cand_higgs": "ATLAS Higgs masks", "sweep_42739": "Road-safety masks"}
ARMS = [("mean_impute", "Imput."), ("mean_indicator", "Indic."), ("mask_interaction", "Inter."), ("ours", "Publ."), ("exact0", "Own rows"), ("family_cv", "CV"), ("histgb", "Tree")]
lines = ["% GENERATED by figures/make_semisynth_table.py --- do not edit by hand.", r"\begin{table}[t]", r"\centering", r"\small",
         r"\caption{Semi-synthetic outcomes on real masks and values (development halves, $60{,}000$ records, one 70/30 split). "
         r"The outcome is regenerated from a logistic model whose coefficients differ by pattern by a controlled amount $\delta$; "
         r"$\delta = 0$ is one shared linear model. AUPRC per arm; CV is the hierarchy with the fitting rule and $\kappa$ chosen by inner cross-validation.}",
         r"\label{tab:semisynth}", r"\begin{tabular}{lr" + "r" * len(ARMS) + "}", r"\toprule", r"Masks & $\delta$ & " + " & ".join(a[1] for a in ARMS) + r" \\", r"\midrule"]
for f in sorted(glob.glob(str(ROOT / "results/semisynth_*.csv"))):
    d = pd.read_csv(f); name = NAMES.get(d.dataset.iloc[0], d.dataset.iloc[0]); first = True
    for _, r in d.iterrows():
        lines.append(f"{name if first else ''} & {r.delta:.2f} & " + " & ".join(f"{r[a]:.3f}" for a, _ in ARMS) + r" \\"); first = False
    lines.append(r"\midrule")
lines[-1] = r"\bottomrule"; lines += [r"\end{tabular}", r"\end{table}"]
(ROOT / "tables/semisynth.tex").write_text("\n".join(lines) + "\n"); print("  wrote tables/semisynth.tex")
