"""tables/calibration.tex: calibration slope and intercept per method x cohort (referee request, 2026-09-03).

Reads the SAME cells as the main table: every committed result file ingest_results.py reads, restricted to
subsample_n = FULL_SUBSAMPLE_N and feature_set = baseline, de-duplicated on (cohort, method, feature_set, seed,
fold) keep="first" in the same source order. Mean over the 50 (seed, fold) cells. Slope 1 / intercept 0 is
perfect calibration (logistic recalibration of the predicted logits, hgmiss.metrics).
"""
import pathlib, sys
import numpy as np, pandas as pd
HERE = pathlib.Path(__file__).resolve().parent; ROOT = HERE.parent
sys.path.insert(0, str(HERE)); sys.path.insert(0, str(ROOT / "src"))
from ingest_results import METHOD_MAP, FULL_SUBSAMPLE_N  # noqa: E402
COHORTS = ["colorectal", "lung", "ovarian", "prostate"]

def load_main_df(results_dir: pathlib.Path) -> pd.DataFrame:
    sources = [results_dir / "main.csv", *sorted(results_dir.glob("main_*.csv")),
               *sorted(results_dir.glob("rebuild-*/main.csv")), *sorted(results_dir.glob("FULL-*/main.csv")),
               *sorted(results_dir.glob("FULLX-*.csv"))]
    frames = []
    for s in sources:
        if not s.exists(): continue
        try: d = pd.read_csv(s)
        except Exception: continue
        if {"cohort", "method", "auprc", "seed", "fold", "calibration_slope", "calibration_intercept"} <= set(d.columns): frames.append(d)
    df = pd.concat(frames, ignore_index=True)
    df = df[df.subsample_n == FULL_SUBSAMPLE_N]
    return df.drop_duplicates(subset=["cohort", "method", "feature_set", "seed", "fold"], keep="first")

def main():
    df = load_main_df(ROOT / "results"); df = df[df.feature_set == "baseline"]
    df["cohort"] = df["cohort"].str.lower()
    g = df.groupby(["method", "cohort"]).agg(slope=("calibration_slope", "mean"), intercept=("calibration_intercept", "mean"),
                                             brier=("brier", "mean"), n=("auprc", "size")).reset_index()
    counts = g.pivot(index="method", columns="cohort", values="n")
    lines = ["% GENERATED by figures/make_calibration_table.py --- do not edit by hand.", r"\begin{table}[t]", r"\centering", r"\small",
             r"\caption{Calibration on the PLCO cohorts, primary analysis (same cells as Table~\ref{tbl:main}: 10 seeds $\times$ 5 folds, "
             r"$n = 40{,}000$). Slope and intercept of the logistic recalibration of the predicted logits on the test fold, "
             r"mean over cells; $1$ and $0$ are perfect. Brier scores are in the released results.}",
             r"\label{tbl:calibration}", r"\begin{tabular}{l" + "rr" * 4 + "}", r"\toprule",
             "Method & " + " & ".join(rf"\multicolumn{{2}}{{c}}{{{c.capitalize()}}}" for c in COHORTS) + r" \\",
             " & " + " & ".join(["slope & int."] * 4) + r" \\", r"\midrule"]
    for m, (fam, label) in METHOD_MAP.items():
        if m not in g.method.values: continue
        cells = []
        for c in COHORTS:
            r = g[(g.method == m) & (g.cohort == c)]
            cells.append("--- & ---" if r.empty or int(r.n.iloc[0]) < 50 else f"{r.slope.iloc[0]:.2f} & {r.intercept.iloc[0]:+.2f}")
        lines.append(f"{label} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    (ROOT / "tables" / "calibration.tex").write_text("\n".join(lines) + "\n")
    print(f"  wrote tables/calibration.tex; cells per method:\n{counts.to_string()}")
    g.to_csv(ROOT / "results" / "calibration_summary.csv", index=False)

if __name__ == "__main__":
    main()
