"""tables/mimic.tex + tables/mimic_counts.tex from results/ideas/M1/*.csv (the pre-registered MIMIC-IV run).
Same pairing as score_mimic.py: paired within (seed, fold), median difference, Wilcoxon. GENERATED."""
import pathlib, numpy as np, pandas as pd
from scipy import stats
HERE = pathlib.Path(__file__).resolve().parent; ROOT = HERE.parent
parts = [f for f in sorted((ROOT / "results/ideas/M1").glob("mimic4*.csv")) if ".smoke" not in f.name]
d = pd.concat([pd.read_csv(f) for f in parts]).drop_duplicates(subset=["arm", "permuted", "seed", "fold"])
d["arm"] = d.arm.str.replace("idea_M1_", "", regex=False)
assert len(d) == 800, len(d)
real = d[d.permuted == 0].pivot_table(index=["seed", "fold"], columns="arm", values="auprc")
null = d[d.permuted == 1].pivot_table(index=["seed", "fold"], columns="arm", values="auprc")
NAMES = [("mean_impute", "Mean imputation + logistic"), ("mean_indicator", "Mean imputation + indicator"), ("mask_interaction", "Mask-interaction expansion"),
         ("histgb_native", "HistGradientBoosting (native)"), ("pattern_submodels", "Pattern submodels"), ("spsm_global", "SPSM (global)"),
         ("ours", "Proposed method"), ("rooted_cv", "Proposed, re-rooted, CV $\\kappa$")]
def pm(a, b, piv):
    x = (piv[a] - piv[b]).to_numpy(); x = x[np.isfinite(x)]
    return float(np.median(x)), (float(stats.wilcoxon(x).pvalue) if np.any(x != 0) else 1.0)
lines = ["% GENERATED by figures/make_mimic_table.py --- do not edit by hand.", "\\begin{table}[t]", "\\centering", "\\small",
         "\\caption{MIMIC-IV, pre-registered test (\\texttt{prereg/MIMIC.md}): first ICU stay, 42 first-24-hour laboratory values, in-hospital mortality, $n = 66{,}989$, 10 seeds $\\times$ 5 folds. Mean AUPRC; paired median difference from mean imputation and Wilcoxon $p$; the null column is the same difference under the permuted mask. The pre-registered predictions and their outcomes are in Section~\\ref{sec:res-mimic}.}",
         "\\label{tbl:mimic}", "\\begin{tabular}{lrrrr}", "\\toprule", "Method & AUPRC & $\\Delta$ vs.\\ imputation & $p$ & $\\Delta$ under null \\\\", "\\midrule"]
mac = ["% GENERATED by figures/make_mimic_table.py --- do not edit by hand."]
for k, name in NAMES:
    m, p = pm(k, "mean_impute", real); mn, _ = pm(k, "mean_impute", null) if k != "mean_impute" else (0.0, 1.0)
    lines.append(f"{name} & {real[k].mean():.4f} & {'---' if k=='mean_impute' else f'{m:+.4f}'} & {'---' if k=='mean_impute' else f'{p:.1e}'} & {'---' if k=='mean_impute' else f'{mn:+.4f}'} \\\\")
lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
(ROOT / "tables/mimic.tex").write_text("\n".join(lines) + "\n")
m2, p2 = pm("ours", "mean_impute", real); m3, _ = pm("ours", "mean_indicator", real); m5b, _ = pm("ours", "pattern_submodels", real); m5a, _ = pm("ours", "spsm_global", real); m6, _ = pm("rooted_cv", "mean_impute", real)
ex = ((real["ours"] - real["mean_impute"]) - (null["ours"] - null["mean_impute"])).to_numpy(); exm = float(np.median(ex)); exp_ = float(stats.wilcoxon(ex).pvalue)
mh, _ = pm("histgb_native", "mean_impute", real); mi, _ = pm("mean_indicator", "mean_impute", real); mmi, _ = pm("mask_interaction", "mean_impute", real)
kc = pd.to_numeric(d[(d.permuted == 0) & (d.arm == "rooted_cv")].kappa_chosen, errors="coerce"); k0 = float(np.mean(kc == 0))
import json; g = json.load(open(ROOT / "results/ideas/M1/mimic4.diag.json")); iota = float(np.mean([f["iota"] for f in g["train_folds"]])); hexc = float(np.mean([f["het_excess"] for f in g["train_folds"]]))
for k, v in {"MimicN": f"{g['n']:,}", "MimicD": g["d"], "MimicPrev": f"{100*g['prev']:.1f}", "MimicIota": f"{iota:.2f}", "MimicHexc": f"{hexc:+.2f}",
             "MimicOursVsImpute": f"{m2:+.4f}", "MimicOursVsImputeP": f"{p2:.1e}", "MimicOursVsIndicator": f"{m3:+.4f}", "MimicOursVsSubmodels": f"{m5b:+.4f}", "MimicOursVsSpsm": f"{m5a:+.4f}",
             "MimicExcess": f"{exm:+.4f}", "MimicExcessP": f"{exp_:.1e}", "MimicIndicatorVsImpute": f"{mi:+.4f}", "MimicInteractionVsImpute": f"{mmi:+.4f}", "MimicHistgbVsImpute": f"{mh:+.4f}",
             "MimicRootedVsImpute": f"{m6:+.4f}", "MimicKappaZeroPct": f"{100*k0:.0f}", "MimicHistgbNull": f"{pm('histgb_native','mean_impute',null)[0]:+.4f}", "MimicIndicatorNull": f"{pm('mean_indicator','mean_impute',null)[0]:+.4f}",
             "MimicHistgbExcess": f"{mh - pm('histgb_native','mean_impute',null)[0]:+.4f}", "MimicIndicatorExcess": f"{mi - pm('mean_indicator','mean_impute',null)[0]:+.4f}",
             "MimicHistgbVsIndicator": f"{pm('histgb_native','mean_indicator',real)[0]:+.4f}", "MimicNullOursVsImpute": f"{pm('ours','mean_impute',null)[0]:+.4f}"}.items():
    mac.append(f"\\newcommand{{\\{k}}}{{{v}}}")
(ROOT / "tables/mimic_counts.tex").write_text("\n".join(mac) + "\n"); print("  wrote tables/mimic.tex and tables/mimic_counts.tex")
