"""Emit tables/synth_counts.tex and tables/synthhet_rows.tex from the synthetic suite.

Paper 1's synthetic results were typed into the text and into Table synthhet by hand. They come
from results/synthetic_suite_1se.csv (the conservative kappa rule), results/synthetic_suite.csv
(plain inner-CV argmax) and results/diagnostic_validation.csv. Written 2026-09-23 for SYNTHRERUN
(prereg/SYNTHRERUN.md); against the August files every macro reproduced the typed value.

A significant win or loss is delta against the tuned indicator model at Wilcoxon p < 0.05. The
table's bracketed fraction is the share of significant WINS in the cell, as its caption says.
"""
import pathlib

import pandas as pd
from scipy import stats

HERE = pathlib.Path(__file__).resolve().parent
R = HERE.parent / "results"
T = HERE.parent / "tables"

s = pd.read_csv(R / "synthetic_suite_1se.csv")
a = pd.read_csv(R / "synthetic_suite.csv")
dv = pd.read_csv(R / "diagnostic_validation.csv")
# validate_diagnostic.py writes one row per suite row, in suite order, but its `het` column is
# the measured statistic, which overwrote the generator's level. Recover the level by position,
# and refuse if the rows do not line up.
key = ["mechanism", "info", "concentration", "n"]
if len(dv) != len(s) or not (dv[key].reset_index(drop=True) == s[key].reset_index(drop=True)).all().all():
    raise SystemExit("diagnostic_validation.csv is not row-aligned with synthetic_suite_1se.csv")
dv["level"] = s["het"].to_numpy()

D, P = "delta_vs_tuned_ind", "p_vs_tuned_ind"
win = lambda d: (d[D] > 0) & (d[P] < 0.05)
loss = lambda d: (d[D] < 0) & (d[P] < 0.05)
f4 = lambda x: f"{x:+.4f}"

HET = {0.0: "Zero", 0.5: "Half", 1.5: "Hi"}
CONC = {0.1: "Low", 0.5: "Mid", 0.9: "High"}
vals = [("SyConfigs", f"{len(s)}"), ("SyWins", f"{int(win(s).sum())}"), ("SyLosses", f"{int(loss(s).sum())}"),
        ("SyArgWins", f"{int(win(a).sum())}"), ("SyArgLosses", f"{int(loss(a).sum())}"),
        ("SyArgWorst", f"{a.loc[loss(a), D].min():+.3f}"),
        ("SyGainCost", f"{int(win(a).sum()) - int(win(s).sum())}"),
        ("SyMean", f4(s[D].mean())), ("SyArgMean", f4(a[D].mean()))]
lv = sorted(s.loc[loss(s), D], reverse=True)
vals.append(("SyLossList", " and ".join(f"${v:+.4f}$" for v in lv) if lv else "none"))
cells = {}
for h, hn in HET.items():
    for c, cn in CONC.items():
        g = s[(s.het == h) & (s.concentration == c)]
        cells[(h, c)] = (g[D].mean(), win(g).mean())
        vals += [(f"SyCell{hn}{cn}", f4(g[D].mean())), (f"SyFrac{hn}{cn}", f"{win(g).mean():.2f}")]
for h, hn in [(1.5, "Hi"), (0.0, "Zero")]:
    for i, iname in [(0.0, "Off"), (1.5, "On")]:
        vals.append((f"SyInfo{hn}{iname}", f4(s[(s.het == h) & (s["info"] == i)][D].mean())))
vals.append(("SyIotaRho", f"{stats.spearmanr(dv.iota, dv.delta).statistic:.2f}"))
# the linear fit in Figure maskinfo; it can rise while the ranks do not, when a few large gains lead
vals.append(("SyIotaPearson", f"{stats.pearsonr(dv.iota, dv.delta)[0]:.2f}"))
for h, hn in HET.items():
    g = dv[dv.level == h]
    vals.append((f"SyIotaRho{hn}", f"{stats.spearmanr(g.iota, g.delta).statistic:.2f}"))
lo = dv.iota < 0.05
for m, nm in [(lo, "Lo"), (~lo, "Hi")]:
    g = dv[m]
    vals += [(f"SyIota{nm}Mean", f4(g.delta.mean())), (f"SyIota{nm}Pos", f"{int((g.delta > 0).sum())}"),
             (f"SyIota{nm}N", f"{int(m.sum())}")]

with open(T / "synth_counts.tex", "w") as f:
    f.write("% generated by figures/make_synth_table.py from results/synthetic_suite_1se.csv, "
            "synthetic_suite.csv and diagnostic_validation.csv -- do not edit\n")
    for k, v in vals:
        f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")

# body rows of Table synthhet; the two strongest cells are set in bold, as the text discusses them
best = sorted(cells, key=lambda k: cells[k][0], reverse=True)[:2]
# the whole tabular, not only its rows: \input is not expandable inside a tabular, so an input
# placed between \midrule and \bottomrule leaves the rule misplaced
with open(T / "synthhet_rows.tex", "w") as f:
    f.write("% generated by figures/make_synth_table.py -- do not edit\n")
    f.write("\\begin{tabular}{lccc}\n\\toprule\n & \\multicolumn{3}{c}{pattern concentration} \\\\\n"
            "\\cmidrule(l){2-4}\n$\\lambda_{\\mathrm{het}}$ & 0.1 & 0.5 & 0.9 \\\\\n\\midrule\n")
    for h in HET:
        parts = []
        for c in CONC:
            m, fr = cells[(h, c)]
            v = f"\\mathbf{{{f4(m)}}}" if (h, c) in best else f4(m)
            parts.append(f"${v}$ ({fr:.2f})")
        f.write(f"{h:.1f} & " + " & ".join(parts) + " \\\\\n")
    f.write("\\bottomrule\n\\end{tabular}\n")
print(f"synth_counts.tex ({len(vals)} macros) and synthhet_rows.tex written")
for k, v in vals:
    print(f"  {k:18s} {v}")
