"""Emit tables/maskwide_counts.tex from the committed MASKWIDE results.

MASKWIDE (prereg/MASKWIDE.md, Result 233) asks whether the containment hierarchy beats flat
indicators once value columns are withheld and the full mask is kept. Nothing in the paper's
schema-width paragraph is typed by hand.

Run from the paper directory:
    .venv/bin/python figures/make_maskwide_table.py
"""
import glob, pathlib
import numpy as np
import pandas as pd
from scipy import stats

HERE = pathlib.Path(__file__).resolve().parent
R = HERE.parent / "results" / "maskwide"
OUT = HERE.parent / "tables"
PROTOCOL = ["cand_eicu_regime", "cand_mimic4_regime", "cand_nhanes", "sweep_42739"]
# realised patterns per dataset, counted from the cached matrices; fixed in prereg/MASKWIDE.md
PATTERNS = {"cand_eicu_regime": 35188, "cand_mimic4_regime": 9448, "cand_acs_income": 1723,
            "sweep_42093": 1256, "sweep_42739": 986, "sweep_42333": 782, "cand_nhanes": 593,
            "cand_porto": 82, "sweep_42737": 38, "sweep_42136": 35, "cand_airbnb": 33,
            "sweep_46725": 24, "sweep_42080": 19, "sweep_41275": 17, "sweep_46703": 7,
            "cand_higgs": 6, "sweep_46654": 5}

d = pd.concat([pd.read_csv(f) for f in sorted(glob.glob(str(R / "*.csv")))], ignore_index=True)
w = d.pivot_table(index=["dataset", "q", "draw", "fold", "permuted"],
                  columns="arm", values="auprc").reset_index()
w["gain"] = w["family_cv"] - w["mean_indicator"]
g = w.groupby(["dataset", "q", "draw", "permuted"]).gain.mean().reset_index()
real, null = g[g.permuted < 0], g[g.permuted >= 0]
NARROW, FULL = 0.1, 1.0
floor = float(np.percentile(null[null.q == NARROW].gain, 95))
rp = real.groupby(["dataset", "q"]).gain.mean().unstack("q")
above = rp[NARROW] > floor

def rho(q):
    ds = [x for x in rp.index if x in PATTERNS and not np.isnan(rp.loc[x, q])]
    return stats.spearmanr(np.log10([PATTERNS[x] for x in ds]), rp.loc[ds, q].to_numpy(float))[0]

vals = [("MwData", int(rp.shape[0])), ("MwNull", int(null.permuted.nunique())),
        ("MwFloor", f"{floor:+.4f}"),
        ("MwAbove", int(above.sum())),
        ("MwProtAbove", int(sum(bool(above.get(x, False)) for x in PROTOCOL))),
        ("MwProt", len(PROTOCOL)),
        ("MwRhoFull", f"{rho(FULL):+.2f}"), ("MwRhoNarrow", f"{rho(NARROW):+.2f}"),
        ("MwNhanes", f"{rp.loc['cand_nhanes', NARROW]:+.3f}"),
        ("MwEicu", f"{rp.loc['cand_eicu_regime', NARROW]:+.3f}"),
        ("MwMimic", f"{rp.loc['cand_mimic4_regime', NARROW]:+.3f}"),
        ("MwPatMax", f"{max(PATTERNS.values()):,}".replace(",", "{,}")),
        ("MwPatMin", min(PATTERNS.values()))]
with open(OUT / "maskwide_counts.tex", "w") as f:
    f.write("% generated by figures/make_maskwide_table.py -- do not edit\n")
    for k, v in vals:
        f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
print(f"maskwide_counts.tex written ({len(vals)} macros)")
print(f"  floor {floor:+.4f}; above on {int(above.sum())} of {rp.shape[0]}; "
      f"protocol {sum(bool(above.get(x, False)) for x in PROTOCOL)} of {len(PROTOCOL)}")
print(f"  rho: full {rho(FULL):+.3f}  narrow {rho(NARROW):+.3f}")
