"""tables/projection.tex from results/ideas/PROJ/{mimic4,eicu}.csv (Result 167, prereg/PROJECTION.md).

One row per (dataset, drop): AUPRC of the tuned indicator, the published estimator, and the estimator with the
shrunk test-time projection; prevalence in the header so the collapse rows can be read against it.
"""
import pathlib
import pandas as pd
HERE = pathlib.Path(__file__).resolve().parent.parent
D = HERE / "results" / "ideas" / "PROJ"; OUT = HERE / "tables" / "projection.tex"
NAMES = {"mimic4": "MIMIC-IV holdout", "eicu": "eICU holdout"}
DROPS = ["none", "male", "age", "all_six"]

def main():
    lines = ["% GENERATED by figures/make_projection_table.py --- do not edit by hand.",
             r"\begin{table}[t]", r"\centering", r"\small",
             r"\caption{Pre-registered reduced-panel test (\texttt{prereg/PROJECTION.md}) on the holdout halves of "
             r"MIMIC-IV and eICU. AUPRC of the tuned mean-imputation-plus-indicator model, the estimator as published, "
             r"the estimator with the shrunk test-time projection, and the gradient-boosted tree with native "
             r"missing-value handling, when a variable that every (or nearly every) training sample recorded is removed "
             r"at test time. Rows at prevalence are the collapse.}",
             r"\label{tab:projection}",
             r"\begin{tabular}{lrrrr}", r"\toprule",
             r"Removed at test & Indicator & Published & Projected & Tree \\", r"\midrule"]
    for name in ["mimic4", "eicu"]:
        f = D / f"{name}.csv"; assert f.exists(), f
        d = pd.read_csv(f); piv = d.pivot_table(index="drop", columns="arm", values="auprc"); prev = float(d["prevalence"].iloc[0])
        assert len(piv) == 8, (name, len(piv))
        labs = [r for r in piv.index if r not in DROPS]
        order = ["none", "male", "age", *sorted(labs), "all_six"]
        lines.append(f"\\multicolumn{{5}}{{l}}{{\\emph{{{NAMES[name]}, prevalence {prev:.3f}}}}} \\\\")
        for drop in order:
            r = piv.loc[drop]
            label = {"none": "none (baseline)", "all_six": "all six"}.get(drop, drop.lower())
            lines.append(f"\\quad {label} & {r['mean_indicator']:.3f} & {r['ours']:.3f} & {r['ours_projected']:.3f} & {r['histgb_native']:.3f} \\\\")
        lines.append(r"\midrule")
    lines[-1] = r"\bottomrule"
    lines += [r"\end{tabular}", r"\end{table}"]
    OUT.write_text("\n".join(lines) + "\n"); print(f"  wrote {OUT.relative_to(HERE)} ({len(lines)} lines)")

if __name__ == "__main__":
    main()
