#!/usr/bin/env python3
"""
Generate the paper's results tables from the same CSVs the figures read.

>>> EVERY NUMBER IS MOCK <<<
Emits ../tables/*.tex, each value wrapped in \\MOCK{} so it renders red and
cannot reach a reviewer unnoticed. Set MOCK = False (here and in
make_figures.py) once real_*.csv exist; the \\MOCK{} wrapper then disappears.

Run:  python make_tables.py
"""

import csv
import os

MOCK = False
RESULTS_CSV = "mock_results.csv" if MOCK else "real_results.csv"
COHORTS_CSV = "mock_cohorts.csv" if MOCK else "real_cohorts.csv"
OUT = "../tables"

COHORTS = ["Colorectal", "Lung", "Ovarian", "Prostate"]
SHORT = ["Col.", "Lung", "Ova.", "Pro."]
KEY = [c.lower() for c in COHORTS]

# Paired-difference CIs vs SPSM, mirroring pair_ci in make_figures.py.
# A gap is significant iff it exceeds its paired CI.
# The paired ours-vs-SPSM interval per cohort, measured. This was
# SPSM_PAIR_CI = [0.009, 0.008, 0.012, 0.016], invented alongside the mock table and roughly 35x
# too wide: the real half-widths are 0.00025 and 0.00024 on the two finished cohorts. That is not
# a cosmetic difference. Under the mock width the difference against SPSM sat inside the interval
# and the table called it a tie; under the measured interval it excludes zero on both cohorts and
# is significant -- while remaining smaller than the 0.002 attainable-gain floor. Both readings
# end at "no meaningful gain over SPSM", by different routes, and only one of them is true.
FLOOR = 0.002          # the attainable-gain floor, as in sections-experiment.tex


def load_spsm_pairs(path="real_spsm_pairs.csv"):
    """cohort -> measured paired stats. Absent file or cohort means the marks are omitted
    rather than guessed."""
    try:
        with open(path) as f:
            return {r["cohort"]: r for r in csv.DictReader(f)}
    except OSError:
        print(f"  NOTE: {path} not found; SPSM significance marks omitted")
        return {}

FAMILY_LABEL = {
    "impute": "Impute-then-learn",
    "mask": "Mask-augmented",
    "native": "Native missing",
    "pattern": "Pattern-conditioned",
    "ours": "Ours",
}


def load(path):
    with open(path) as f:
        return [r for r in csv.DictReader(
            line for line in f if not line.lstrip().startswith("#"))]


def m(s):
    return f"\\MOCK{{{s}}}" if MOCK else s


def main():
    os.makedirs(OUT, exist_ok=True)
    res = load(RESULTS_CSV)
    spsm_pairs = load_spsm_pairs()
    coh = load(COHORTS_CSV)

    # ---------------------------------------------------------- cohort table
    lines = [
        "% GENERATED by figures/make_tables.py --- do not edit by hand.",
        "\\begin{table}[t]", "\\centering",
        "\\caption{PLCO cohorts after preprocessing. $n$ is the full cohort; $|\\mathcal{E}|$, $\\iota$ and the fallback rate are measured on the 40{,}000-record analysis sample of Section~\\ref{sec:evalsetup}. \\%pos is the minority (death within "
        "five years) prevalence, which is also the AUPRC baseline. $|\\mathcal{E}|$ is the "
        "number of realised missingness patterns, against a bound of $\\min(2^d, n)$. "
        "$\\iota$ is mask informativeness (Eq.~\\ref{eq:maskinfo}). Fallback is the rate at "
        "which no pattern is applicable and the marginal value is returned.}",
        "\\label{tbl:cohorts}",
        "\\begin{tabular}{lrrrrrrr}", "\\toprule",
        "Cohort & $n$ & $d$ & \\%miss & \\%pos & $|\\mathcal{E}|$ & $\\iota$ & "
        "Fallback (\\%) \\\\",
        "\\midrule",
    ]
    for r in coh:
        n_fmt = m("{:,}".format(int(r["n"])))
        iota_fmt = m("{:.3f}".format(float(r["iota"])))
        fb_fmt = m("{:.1f}".format(float(r["fallback"]) * 100))
        lines.append(
            "{} & {} & {} & {} & {} & {} & {} & {} \\\\".format(
                r["cohort"], n_fmt, m(r["d"]), m("{:.1f}".format(float(r["pct_miss"]))),
                m("{:.1f}".format(float(r["pct_pos"]))), m("{:,}".format(int(float(r["patterns"])))), iota_fmt, fb_fmt))
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    open(f"{OUT}/cohorts.tex", "w").write("\n".join(lines) + "\n")
    print(f"  wrote {OUT}/cohorts.tex")

    # ----------------------------------------------------------- main results
    # Prevalence and majority-class accuracy come from the cohort table, not from the caption
    # text. They were hardcoded as 8.4/12.1/6.9/9.7% prevalence, which is not what these
    # cohorts have -- the measured values are near 3.9/3.9/2.6/5.1%.
    _pv = {}
    for _r in coh:
        try:
            _pv[str(_r["cohort"]).lower()] = float(_r["prevalence"]) if "prevalence" in _r else float(_r["pct_pos"]) / 100
        except (KeyError, ValueError, TypeError):
            pass
    _prev = ", ".join(f"{_pv[k.lower()] * 100:.1f}" for k in KEY if k.lower() in _pv) + "\\%"
    _maj = ", ".join(f"{(1 - _pv[k.lower()]) * 100:.1f}" for k in KEY if k.lower() in _pv) + "\\%"
    spsm = next(r for r in res if r["method"] == "SPSM")
    ours = next(r for r in res if r["family"] == "ours")
    # A cohort still running has empty cells. Skip it rather than crashing on float(""), and
    # give it no "best" so nothing is bolded in a column with no data. The alternative --
    # coercing blanks to 0.0 -- would silently bold whichever method happened to sort first
    # in an empty column.
    def _vals(col):
        return [float(r[col]) for r in res if str(r.get(col, "")).strip() != ""]

    best = {k: (max(_vals(k)) if _vals(k) else None) for k in KEY}
    best_acc = {k: (max(_vals("acc_" + k)) if _vals("acc_" + k) else None) for k in KEY}
    best_roc = {k: (max(_vals("auroc_" + k)) if _vals("auroc_" + k) else None) for k in KEY}
    _absent = [k for k in KEY if best[k] is None]
    if _absent:
        print(f"  NOTE: no data for {_absent}; those columns render as '--' and bold nothing")

    lines = [
        "% GENERATED by figures/make_tables.py --- do not edit by hand.",
        "\\begin{table}[t]", "\\centering",
        "\\caption{Classification result on the PLCO cohorts. Each value is the mean over "
        "10 seeds $\\times$ 5-fold stratified cross-validation. Best per cohort in bold; a column "
        "of dashes is a cohort whose run has not finished. "
        "$\\dagger$: the paired difference against SPSM has a 95\\% bootstrap confidence "
        "interval containing zero. $\\ddagger$: the interval excludes zero but the difference "
        "is smaller than the $0.002$ attainable-gain floor. The majority-class accuracy is " + _maj + ". The AUPRC "
        "of a model which does not use the variables is the prevalence, " + _prev + ".}",
        "\\label{tbl:main}", "\\small",
        "\\setlength{\\tabcolsep}{3pt}",
        "\\fitwidth{%",
        "\\begin{tabular}{ll cccc c cccc c cccc}", "\\toprule",
        "& & \\multicolumn{4}{c}{Accuracy (\\%)} & & \\multicolumn{4}{c}{AUROC} & & "
        "\\multicolumn{4}{c}{AUPRC} \\\\",
        "\\cmidrule(lr){3-6} \\cmidrule(lr){8-11} \\cmidrule(lr){13-16}",
        "Family & Method & " + " & ".join(SHORT) + " & & " + " & ".join(SHORT)
        + " & & " + " & ".join(SHORT) + " \\\\",
        "\\midrule",
    ]
    last = None
    for r in res:
        fam = r["family"]
        if last is not None and fam != last:
            lines.append("\\midrule")
        # A cell with no value renders as a dash. It must be visibly absent rather than
        # blank: a blank cell in a printed table reads as an oversight, and a zero would
        # read as a measurement.
        def _cell(col, prec, bestmap, key):
            raw = str(r.get(col, "")).strip()
            if raw == "":
                return "--"
            v = float(raw)
            b = bestmap.get(key)
            if b is not None and abs(v - b) < 1e-9:
                return f"\\textbf{{{v:.{prec}f}}}"
            return f"{v:.{prec}f}"

        acc = [m(_cell("acc_" + k, 1, best_acc, k)) for k in KEY]
        roc = [m(_cell("auroc_" + k, 3, best_roc, k)) for k in KEY]
        prc = []
        for k in KEY:
            raw = str(r.get(k, "")).strip()
            if raw == "":
                prc.append(m("--"))
                continue
            v = float(raw)
            s = f"{v:.3f}"
            if best[k] is not None and abs(v - best[k]) < 1e-9:
                s = f"\\textbf{{{v:.3f}}}"
            if fam == "ours":
                _pr = spsm_pairs.get(k)
                if _pr:
                    _lo, _hi = float(_pr["ci_lo"]), float(_pr["ci_hi"])
                    _md = float(_pr["median_diff"])
                    if _lo <= 0.0 <= _hi:
                        s += "$^\\dagger$"        # interval contains zero: not distinguishable
                    elif abs(_md) < FLOOR:
                        s += "$^\\ddagger$"       # distinguishable, but below the floor
            prc.append(m(s))
        label = FAMILY_LABEL[fam] if fam != last else ""
        lines.append(f"{label} & {r['method']} & " + " & ".join(acc) + " & & "
                     + " & ".join(roc) + " & & " + " & ".join(prc) + " \\\\")
        last = fam
    lines += ["\\bottomrule", "\\end{tabular}}", "\\end{table}"]
    open(f"{OUT}/main_results.tex", "w").write("\n".join(lines) + "\n")
    print(f"  wrote {OUT}/main_results.tex")

    # ------------------------------------------------- what actually happened
    # Only cohorts with data can be won, lost or tied. Counting an unfinished cohort as a
    # loss would understate the method and as a win would overstate it; it is neither.
    _done = [k for k in KEY
             if str(ours.get(k, "")).strip() != "" and str(spsm.get(k, "")).strip() != ""]
    won = [k for k in _done if best[k] is not None and abs(float(ours[k]) - best[k]) < 1e-9]
    lost = [k for k in _done if float(ours[k]) < float(spsm[k])]
    sig = [k for k in _done
           if k in spsm_pairs and float(spsm_pairs[k]["ci_lo"]) > 0.0]
    below_floor = [k for k in sig if abs(float(spsm_pairs[k]["median_diff"])) < FLOOR]
    tied = [k for k in _done if k not in sig and k not in lost]
    _pending = [k for k in KEY if k not in _done]
    print(f"\n  best on {len(won)}/{len(_done)} finished ({', '.join(won) or 'none'})"
          + (f";  {len(_pending)} cohort(s) not finished: {', '.join(_pending)}" if _pending else ""))
    print(f"  of those significant wins, {len(below_floor)} fall BELOW the {FLOOR} floor "
          f"({', '.join(below_floor) or 'none'})")
    print(f"  vs SPSM: significant win on {len(sig)} ({', '.join(sig) or 'none'}); "
          f"tie on {len(tied)} ({', '.join(tied) or 'none'}); "
          f"LOSS on {len(lost)} ({', '.join(lost) or 'none'})")
    print("  -> the paper's text must say exactly that. Check the abstract "
          "and conclusion if you change these numbers.")
    def spread(prefix):
        widths = []
        for k in KEY:
            vals = [float(r[prefix + k]) for r in res
                    if str(r.get(prefix + k, "")).strip() != ""]
            if vals:
                widths.append(max(vals) - min(vals))
        return max(widths) if widths else float("nan")
    acc_r = spread("acc_")
    roc_r = spread("auroc_") * 100
    prc_r = spread("") * 100
    # The method count comes from the table, not from a number typed into the string. It said
    # "12 methods" while the real run had a different number, and it will say it again the
    # next time a baseline is added or dropped.
    print(f"  spread across the {len(res)} methods: accuracy {acc_r:.1f} pts | "
          f"AUROC {roc_r:.1f} pts | AUPRC {prc_r:.1f} pts")
    print("  -> all three are reported; AUPRC is used for ranking.")
    print("\n  derived means quoted in the prose --- check these against the text:")
    for r in res:
        _vk = [float(r[k]) for k in KEY if str(r.get(k, "")).strip() != ""]
        mu = (sum(_vk) / len(_vk)) if _vk else float("nan")
        print(f"    {r['method']:<32s} mean AUPRC {mu:.3f}")
    o = next(r for r in res if r["family"] == "ours")
    _fin = [k for k in KEY
            if str(o.get(k, "")).strip() != "" and str(spsm.get(k, "")).strip() != ""]
    om = (sum(float(o[k]) for k in _fin) / len(_fin)) if _fin else float("nan")
    sm = (sum(float(spsm[k]) for k in _fin) / len(_fin)) if _fin else float("nan")
    print(f"    -> ours - SPSM = {om - sm:+.3f}  (H2)")


if __name__ == "__main__":
    print("GENERATING TABLES  [MOCK DATA]" if MOCK else "GENERATING TABLES  [real]")
    main()
