"""tables/tunetree.tex from results/tune_tree_*.csv (Result 171): default vs inner-CV-tuned HistGradientBoosting,
3 seeds x 5 folds on the 40,000-record analysis sample (MIMIC-IV: full n), beside the main table's tuned mean
imputation (10 x 5, same rows, different folds -- not paired)."""
import glob, pathlib, re
import pandas as pd
ROOT = pathlib.Path(__file__).resolve().parent.parent
r = pd.read_csv(ROOT / "figures/real_results.csv").set_index("method")
mimic_tex = (ROOT / "tables/mimic.tex").read_text(); _m = re.search(r"Mean imputation \+ logistic & ([0-9.]+)", mimic_tex); MIMIC_IMPUTE = float(_m.group(1)) if _m else None
rows = []
for f in sorted(glob.glob(str(ROOT / "results/tune_tree_*.csv"))):
    d = pd.read_csv(f); c = d.cohort.iloc[0]; assert len(d) == 15, (c, len(d))
    diff = d.auprc_tuned - d.auprc_default; imp = float(r.loc["Mean + logistic", c]) if c in r.columns else MIMIC_IMPUTE
    rows.append((c, d.auprc_default.mean(), d.auprc_tuned.mean(), diff.median(), int((diff > 0).sum()), imp))
order = ["colorectal", "lung", "ovarian", "prostate", "mimic4"]; rows.sort(key=lambda x: order.index(x[0]))
lines = ["% GENERATED by figures/make_tunetree_table.py --- do not edit by hand.", r"\begin{table}[t]", r"\centering", r"\small",
         r"\caption{Tuning the gradient-boosted tree. Mean AUPRC of HistGradientBoosting at library defaults and with a 24-point grid "
         r"(depth, learning rate, number of trees, minimum leaf size) chosen by inner 3-fold cross-validation, 3 seeds $\times$ 5 folds "
         r"on the analysis sample; paired median gain and wins over the default. The last column is the main table's tuned mean "
         r"imputation (10 $\times$ 5 folds on the same rows, different partitions; not paired).}",
         r"\label{tbl:tunetree}", r"\begin{tabular}{lrrrrr}", r"\toprule", r"Cohort & Default & Tuned & Gain & Wins & Tuned imputation \\", r"\midrule"]
for c, a, b, m, w, imp in rows:
    name = {"mimic4": "MIMIC-IV"}.get(c, c.capitalize())
    lines.append(f"{name} & {a:.4f} & {b:.4f} & {m:+.4f} & {w}/15 & " + (f"{imp:.4f}" if imp is not None else "---") + r" \\")
lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
(ROOT / "tables/tunetree.tex").write_text("\n".join(lines) + "\n"); print("  wrote tables/tunetree.tex")
