"""The sensitivity analysis the article promises: does adding follow-up variables change the result?

Compares each method's AUPRC under the FULL feature set against the BASELINE set on the same
(cohort, seed, fold) cells -- the same rows, the same splits, different columns -- so every
difference is paired. Emits tables/sensitivity.tex and tables/sensitivity_counts.tex, both
generated, so the section's prose cannot disagree with its table. Cohorts lacking a complete full
set are skipped and named.
"""
from __future__ import annotations

import pathlib
import sys

import numpy as np
import pandas as pd
from scipy import stats

ROOT = pathlib.Path(__file__).resolve().parent.parent
RD, TAB = ROOT / "results", ROOT / "tables"
FLOOR, N = 0.002, 40_000
NAME = {"mean_impute": "Mean + logistic", "mean_indicator": "Mean + indicator",
        "mask_interaction": "Mean + indicator $\\otimes$ features", "histgb_native": "HistGB",
        "spsm_global": "SPSM", "pattern_submodels": "Pattern submodels", "ours": "Proposed"}
COH = {"lung": "Lung", "ovarian": "Ovarian", "prostate": "Prostate", "colorectal": "Colorectal"}


def frame():
    fr = []
    for f in [RD / "main.csv", *sorted(RD.glob("main_*.csv")), *sorted(RD.glob("rebuild-*/main.csv")),
              *sorted(RD.glob("FULL-*/main.csv")), *sorted(RD.glob("FULLX-*.csv"))]:
        if f.exists():
            try:
                d = pd.read_csv(f)
            except Exception:                                   # noqa: BLE001
                continue
            if {"cohort", "method", "feature_set", "seed", "fold", "auprc"} <= set(d.columns):
                fr.append(d)
    d = pd.concat(fr, ignore_index=True)
    d = d[d.subsample_n == N].drop_duplicates(["cohort", "method", "feature_set", "seed", "fold"])
    return d


def main() -> int:
    d = frame()
    rows, skipped = [], []
    for coh in ("lung", "ovarian", "prostate", "colorectal"):
        b = d[(d.cohort == coh) & (d.feature_set == "baseline")]
        f = d[(d.cohort == coh) & (d.feature_set == "full")]
        shared = sorted(set(b.method) & set(f.method) & set(NAME))
        # Require the COMPLETE main-table set under `full`, not merely that each present method
        # is complete. Colorectal's stub holds one finished method, which satisfied the weaker
        # rule and put a one-method cohort into the comparison -- the same fault the ingest had
        # an hour earlier, reproduced here within minutes of fixing it there.
        if set(shared) != set(NAME) or any(len(f[f.method == m]) < 50 for m in shared):
            skipped.append(coh); continue
        for m in shared:
            pb = b[b.method == m].set_index(["seed", "fold"]).auprc
            pf = f[f.method == m].set_index(["seed", "fold"]).auprc
            x = (pf - pb).dropna().to_numpy(float)
            rows.append(dict(cohort=coh, method=m, n=len(x), baseline=float(pb.mean()),
                             full=float(pf.mean()), delta=float(np.median(x)),
                             p=float(stats.wilcoxon(x).pvalue) if np.any(x != 0) else 1.0,
                             wins=int((x > 0).sum())))
    if skipped:
        print(f"  skipped (full set incomplete): {skipped}")
    r = pd.DataFrame(rows)
    if r.empty:
        raise SystemExit("  no cohort has both feature sets complete -- nothing to compare")
    r.to_csv(ROOT / "figures" / "real_sensitivity.csv", index=False)

    # ranks of the proposed method under each feature set, per cohort
    rk = {}
    for coh in r.cohort.unique():
        for fs in ("baseline", "full"):
            sub = d[(d.cohort == coh) & (d.feature_set == fs) & d.method.isin(NAME)]
            means = sub.groupby("method").auprc.mean().sort_values(ascending=False)
            rk[(coh, fs)] = (list(means.index).index("ours") + 1, len(means))

    L = ["% GENERATED by figures/sensitivity_compare.py -- do not edit by hand.",
         r"\begin{tabular}{@{}llrrrrr@{}}", r"\toprule",
         r"Cohort & Method & Baseline & Full & $\Delta$ (median) & $p$ & Full $>$ base \\", r"\midrule"]
    for coh, g in r.groupby("cohort", sort=False):
        g = g.sort_values("full", ascending=False)
        for i, (_, w) in enumerate(g.iterrows()):
            lab = f"\\multirow{{{len(g)}}}{{*}}{{{COH[coh]}}}" if i == 0 else ""
            pv = f"{w.p:.1g}"
            if "e" in pv:
                mant, ex = pv.split("e"); pv = f"{mant}\\times10^{{{int(ex)}}}"
            L.append(f"{lab} & {NAME.get(w.method, w.method)} & ${w.baseline:.3f}$ & ${w.full:.3f}$ & "
                     f"${w.delta:+.4f}$ & ${pv}$ & {w.wins}/{w.n} \\\\")
        L.append(r"\midrule")
    L[-1] = r"\bottomrule"; L.append(r"\end{tabular}")
    (TAB / "sensitivity.tex").write_text("\n".join(L) + "\n")

    ours = r[r.method == "ours"]; mi = r[r.method == "mean_impute"]
    gap_b = {c: float(mi[mi.cohort == c].baseline.iloc[0] - ours[ours.cohort == c].baseline.iloc[0]) for c in ours.cohort}
    gap_f = {c: float(mi[mi.cohort == c].full.iloc[0] - ours[ours.cohort == c].full.iloc[0]) for c in ours.cohort}
    (TAB / "sensitivity_counts.tex").write_text(
        "% GENERATED by figures/sensitivity_compare.py -- do not edit by hand.\n"
        f"\\newcommand{{\\SensCohorts}}{{{r.cohort.nunique()}}}\n"
        f"\\newcommand{{\\SensMethods}}{{{r.method.nunique()}}}\n"
        f"\\newcommand{{\\SensOursGainLo}}{{${ours.delta.min():+.3f}$}}\n"
        f"\\newcommand{{\\SensOursGainHi}}{{${ours.delta.max():+.3f}$}}\n"
        f"\\newcommand{{\\SensImputeGainLo}}{{${mi.delta.min():+.3f}$}}\n"
        f"\\newcommand{{\\SensImputeGainHi}}{{${mi.delta.max():+.3f}$}}\n"
        f"\\newcommand{{\\SensGapBaseLo}}{{${min(gap_b.values()):.3f}$}}\n"
        f"\\newcommand{{\\SensGapBaseHi}}{{${max(gap_b.values()):.3f}$}}\n"
        f"\\newcommand{{\\SensGapFullLo}}{{${min(gap_f.values()):.3f}$}}\n"
        f"\\newcommand{{\\SensGapFullHi}}{{${max(gap_f.values()):.3f}$}}\n"
        f"\\newcommand{{\\SensOursRankBase}}{{{'--'.join(sorted({str(rk[(c,'baseline')][0]) for c in ours.cohort}))}}}\n"
        f"\\newcommand{{\\SensOursRankFull}}{{{'--'.join(sorted({str(rk[(c,'full')][0]) for c in ours.cohort}))}}}\n"
        f"\\newcommand{{\\SensRankOf}}{{{rk[(list(ours.cohort)[0],'full')][1]}}}\n")
    print(f"  {len(r)} paired comparisons over {r.cohort.nunique()} cohort(s)")
    for _, w in ours.iterrows():
        print(f"    ours {w.cohort:9s} {w.baseline:.3f} -> {w.full:.3f}  delta {w.delta:+.4f} p={w.p:.2g}  "
              f"| gap to mean_impute {gap_b[w.cohort]:.3f} -> {gap_f[w.cohort]:.3f}")
    print(f"  wrote tables/sensitivity.tex and tables/sensitivity_counts.tex")
    return 0


if __name__ == "__main__":
    sys.exit(main())
